login/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
#from login.views import *
from . import views
from  django.conf import settings
urlpatterns = [
    url(r'^logout/$', views.logout_page, name='logout_page'),
    url(r'^accounts/login/$', views.mylogin, name='mylogin'), # If user is not login it will redirect to login page
    url(r'^register/$', views.register, name='register'),
    url(r'^register/success/$', views.register_success, name='register_success'),
    url(r'^student/$', views.sthome, name='sthome'),
    url(r'^faculty/$', views.fhome, name='fhome'),
    url(r'^addevent/(?P<pk>[0-9]+)/$', views.addevent, name='addevent'),
    url(r'^courseadd/$',views.courseadd, name='courseadd'),
    url(r'^courseregister/$',views.courseregister, name='courseregister'),
    url(r'^coursedisplay/$',views.coursedisplay, name='coursedisplay'),
    url(r'^coursedetail/(?P<pk>[0-9]+)/$',views.coursedetail, name='coursedisplay'),
    url(r'^registeredcourses/$',views.registeredcourses, name='registeredcourses'),
    url(r'^payfees/$',views.payfees, name='payfees'),
    url(r'^feesuccess/$',views.feesuccess,name='feesuccess'),
    url(r'^parent/$',views.parent,name='parent'),
    #url(r'^parentresult/$',views.parentresult,name='parentresult'),
]

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
    )

myapp/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from login.views import mylogin
 
urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',mylogin,name='mylogin'),
    url(r'',include('login.urls',namespace="login")),
]

login/forms.py
import re
from django import forms
import datetime
from .models import Student, Parent, Faculty, Course, Calender, Takes, Teaches, Parenting
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.admin import widgets
from django.forms.extras.widgets import SelectDateWidget


student = 0
faculty = 1
PREFERRED_DRINK_CHOICES = (
    (student, 'Student'),
    (faculty, 'Faculty'),
)

class MySelectDateWidget(SelectDateWidget):

    def create_select(self, *args, **kwargs):
        old_state = self.is_required
        self.is_required = False
        result = super(MySelectDateWidget, self).create_select(*args, **kwargs)
        self.is_required = old_state
        return result


class RegistrationForm(forms.Form):
    CHOICES=[('Student','Student'),('Faculty','Faculty')]
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    firstname = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("First Name"))
    lastname = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Last Name"))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))
    type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(),initial='Student')
    """
        class Meta:
		model=Student
		fields=('name','gender','dob','email')
        """
    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))


    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data



class ProfileForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("First Name"))
    lastname = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Last Name"))
    role = forms.ChoiceField(choices=PREFERRED_DRINK_CHOICES, widget=forms.RadioSelect(),label=_("Role"))


class CourseForm(forms.ModelForm):
    syllabus = forms.CharField(widget=forms.Textarea)
    class Meta:
        model=Course
        fields=('name','instructor','syllabus','prerequisite')




class CourseRegisterForm(forms.ModelForm):
    class Meta:
        model=Takes
        fields=('cid','sid')


class CalenderForm(forms.ModelForm):
    deadline = forms.DateField(label="Scheduled date",required=False,widget=MySelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"),),)
    docfile = forms.FileField(label='Select a file', help_text='max. 42 megabytes')
    event = forms.CharField(widget=forms.Textarea)
    class Meta:
        model=Calender
        fields=('cid','event','deadline','docfile')


class ContactForm(forms.Form):
        subject = forms.CharField(required=True)
        message = forms.CharField(widget=forms.Textarea)
        
        
class ParentForm(forms.Form):
    childid = forms.CharField(required=True)
    emailid = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)))
    #dob = forms.DateField(required=True,widget=MySelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"),),)             

login/views.py
import datetime
from login.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponseRedirect
from django.template import RequestContext
from .models import Student, Course,Faculty,Calender, Teaches, Takes
from django.shortcuts import render, get_object_or_404, redirect,render_to_response
from django.utils import timezone
from django.core.mail import send_mail, EmailMessage

@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            first_name=form.cleaned_data['firstname'],
            last_name=form.cleaned_data['lastname'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            typ=form.cleaned_data['type']
            if(typ=='Student'):
                user.is_staff=0
            else:
                user.is_staff=1
            user.save()
            return HttpResponseRedirect('/register/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request, {
    'form': form
    })

    return render_to_response(
    'registration/register.html',
    variables,
    )

def mylogin(request):

    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            if user.is_staff==True:
                return HttpResponseRedirect('/faculty')
            else:
                return HttpResponseRedirect('/student')

    return render_to_response('registration/login.html',context_instance=RequestContext(request))



def register_success(request):
    return render_to_response(
    'registration/success.html',
    )

def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def sthome(request):
    regcourses=Takes.objects.filter(sid=request.user.id)
    #print regcourses[0].cid
    reg_distinct=[]
    for i in range(0,len(regcourses)):
        reg_distinct.append(regcourses[i].cid)
    reg_distinct = set(reg_distinct)
    #print reg_distinct
    course = Calender.objects.filter(cid__in=reg_distinct,deadline__lte=datetime.datetime.today()+datetime.timedelta(days=10)).order_by('deadline')
    #course.append(Calender.objects.filter(cid__in=reg_distinct,deadline__lte=datetime.datetime.today()+datetime.timedelta(days=10)))
    #course=set(course)
    return render_to_response(
    'student.html',
    { 'user': request.user,'course':course }
    )


@login_required
def fhome(request):
    return render_to_response(
    'faculty.html',
    { 'user': request.user }
    )

@csrf_protect
@login_required
def courseadd(request):
    instance = Course(instructor=request.user)
    form1a = CourseForm(instance=instance)
    form1a.fields['instructor'].widget = forms.HiddenInput()

    if request.method == "POST":
        form1a = CourseForm(request.POST)
        if form1a.is_valid():
            #form1a.instructor=request.user
            #form1a.fields['instructor'].widget.attrs['disabled'] = True
            course = form1a.save(commit=False)
            course.save()
            return redirect('/faculty/',pk=course.pk)
    else:
        form1a = CourseForm(instance=instance)
        form1a.fields['instructor'].widget = forms.HiddenInput()
        #form1a.fields['instructor'].widget.attrs['disabled'] = True
    return render(request,'courseadd.html',{'form1': form1a })


@csrf_protect
@login_required
def courseregister(request):
    instance1 = Takes(sid=request.user)
    regcourses=Takes.objects.filter(sid=request.user.id)
    #print instance1
    form2 = CourseRegisterForm(instance=instance1)
    form2.fields['sid'].widget = forms.HiddenInput()
    #cour = Course.objects.all()
    reg_distinct=[]
    for i in range(0,len(regcourses)):
        reg_distinct.append(regcourses[i].cid)
    reg_distinct = set(reg_distinct)
    #print reg_distinct
    #print getattr(instance1,'sid')
    if request.method == "POST":
        form2 = CourseRegisterForm(request.POST)
        user = request.user
        if form2.is_valid():
            #form2.sid=request.user.id
            course = form2.cleaned_data['cid']
            print course.prerequisite
            print regcourses
            if course in reg_distinct:
                flag="c"
                return render(request,'payfees.html',{'course':course,'flag':flag,'reg_distinct':reg_distinct})
            elif course.prerequisite not in reg_distinct and course.prerequisite!=None:
                flag="b"
                return render(request,'payfees.html',{'course':course,'flag':flag,'reg_distinct':reg_distinct})         
            else:
                flag="a"
                print course    
                #return render(request,'payfees.html',{'course':course,'flag':flag,'reg_distinct':reg_distinct,'fees':100,'n':1})    
                from_email=user.username+"@coursemanagement.com"
                admin_email="no-reply@coursemanagement.com"
                reply_email = user.email
                print flag
                email = EmailMessage(str(course.name)+" enroll", "Please enroll me to the course.\n\n"+"Click on the link to enroll "+str(user)+ " http://localhost:8000", from_email, [course.instructor.email], headers = {'Reply-To': reply_email})
                email.send()
                
                email1 = EmailMessage(str(course.name)+" enrollment", " you have enrolled to the course " +course.name+" with the email id "+user.email+".",admin_email,[user.email])
                email1.send() 
                course_reg = form2.save(commit=False)
                course_reg.save()
                #print form2
                return redirect('/payfees/',pk=course_reg.pk,flag="a",n=1,fees=100)
    else:
        form2 = CourseRegisterForm(instance=instance1)
        form2.fields['sid'].widget = forms.HiddenInput()
        #form2.fields['sid'].widget.attrs['disabled'] = True
        return render(request, 'courseregister.html',{'form2':form2})

@csrf_protect
@login_required
def coursedisplay(request):
    courses=Course.objects.all()
    user=request.user
    return render(request, 'coursedisplay.html',{'user':user,'courses':courses})

@csrf_protect
@login_required
def coursedetail(request,pk):
    course = get_object_or_404(Course, pk=pk)
    user=request.user
    events=Calender.objects.filter(cid=pk).order_by('-time')
    if request.method == 'GET':
        form = ContactForm()
    else:
        form=ContactForm(request.POST);
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email=user.username+"@coursemanagement.com"
            reply_email = user.email
            email = EmailMessage(subject, message, from_email, [course.instructor.email], headers = {'Reply-To': reply_email})
            email.send()

    return render(request, 'coursedetail.html', {'course':course,'events':events,'form':form})


@csrf_protect
@login_required
def registeredcourses(request):
    regcourses=Takes.objects.filter(sid=request.user.id)
    user=request.user
    reg_distinct=[]
    for i in range(0,len(regcourses)):
        reg_distinct.append(regcourses[i].cid)
    reg_distinct = set(reg_distinct)
    #print reg_distinct
    createdcourses=Course.objects.filter(instructor=request.user)
    return render_to_response('registeredcourses.html',{'user':user,'regcourses':reg_distinct,'createdcourses':createdcourses})



@csrf_protect
@login_required
def payfees(request):
    #n=len(Takes.objects.filter(sid=request.user.id))
    n=1
    fees=100
    return render_to_response('payfees.html',{'fees':fees,'n':n})

@csrf_protect
@login_required
def feesuccess(request):
    n=len(Takes.objects.filter(sid=request.user.id))
    fees=100
    return render_to_response('feesuccess.html',{'fees':fees})


@csrf_protect
@login_required
def addevent(request,pk):
    course = get_object_or_404(Course, pk=pk)
    instance_eve = Calender(cid=course)
    formcal = CourseRegisterForm(instance=instance_eve)
    formcal.fields['cid'].widget = forms.HiddenInput()

    #courses = Calender.objects.filter(x__contains=cid)
    #print courses
    formcal = CalenderForm()
    if request.method == "POST":
        formcal = CalenderForm(request.POST,request.FILES)
        if formcal.is_valid():
            #newdoc = Calender(docfile = request.FILES['docfile'])
            #newdoc.save()
            course = formcal.save(commit=False)
            course.save()
            return redirect('/faculty/',pk=course.pk)
    else:
        formcal = CalenderForm(instance=instance_eve)
        formcal.fields['cid'].widget = forms.HiddenInput()
        #formcal.fields['cid'].widget = forms.HiddenInput()
    #events=Calender.objects.all()
    return render(request,'addevent.html',{'formcal': formcal,'course':course })


@csrf_protect
def parent(request):
    """if request.method == 'GET':
        form = ParentForm()
        return render(request,'parent.html',{'form': form})  
        """
    
    """
    form = ParentForm()    
    if request.method == 'POST':
        form=ParentForm(request.POST);
        if form.is_valid():
            childid = form.cleaned_data['childid']
            emailid = form.cleaned_data['emailid']    
            user = User.objects.filter(username=childid)
            print user
            if user.email == emailid:  
                regcourses=Takes.objects.filter(sid=user.username)
                reg_distinct=[]
                for i in range(0,len(regcourses)):

login/templates/addevent.html
{% extends "base.html" %}
{% block title %}Add Events{% endblock %}
{% block head %}Add Events{% endblock %}
{% block content %}
    <ul class="nav">
   <li> <a class="active" href="/faculty/">Home</a></li>

   {% if user.is_staff %}

  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>

    <div class="container">
    <h1><a href="#">{{ course.name }}</a></h1>
    <form method="post" action="."  enctype="multipart/form-data">{% csrf_token %}
        <table border="0">
            {{ formcal.as_table }}
        </table>
        <input type="submit" value="Add Event" />
    </form>
    </div>
{% endblock %}

login/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load staticfiles %}
<html class>
    <head>
        <title>University Course Management Application |
        <link rel="stylesheet" type="text/css" href= "{% static "nav.css" %}" />
        <link rel="stylesheet" href="./font-awesome-4.1.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">


        {% block title %}{% endblock %}</title>
    </head>
    <body style="background-color:#FFFFF2";>
        <div class="header">
            <h1>Course Management</h1>
        </div>
        {% block content %}{% endblock %}
    </body><link rel="stylesheet" type="text/css" href= "{% static "nav.css" %}" />
</html>

login/templates/courseadd.html
{% extends "base.html" %}
{% block title %}Add Courses{% endblock %}
{% block head %}Add Courses{% endblock %}
{% block content %}
    <ul class="nav">
   <li> <a href="/faculty/">Home</a></li>

  <li>  <a class="active" href="/courseadd/">Add Courses</a></li>


   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>
    <div class="container">
    <form method="post" action=".">{% csrf_token %}
        <table border="0">
            
            {{ form1.as_table }}
        </table>
        <input type="submit" value="Add Course" />
    </form>
    </div>
{% endblock %}

login/templates/coursedetail.html
{% extends "base.html" %}
{% block title %}Add Courses{% endblock %}
{% block head %}{% endblock %}
{% block content %}

  <ul class="nav">
   {% if user.is_staff %}
   <li> <a  href="/faculty/">Home</a></li>
  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
    <li> <a  href="/student/">Home</a></li>
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a  href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>
    <div class="container">

        <h1><a href="#">{{ course.name }}</a></h1>
        <p><b><u>Instructor:</b></u> {{ course.instructor.username }}</p>
        <p><b><u>Syllabus:</b></u> {{ course.syllabus }}</p>
        <p><b><u>Prerequisites:</b></u> {{ course.prerequisite.name }}</p>
        
        {% if user.is_staff %}
        {% if course.instructor == user %}
        <p><b>Manage Courses</b></p>
        <h2><a href="{% url "login:addevent" pk=course.pk %}">Add Course Events</a></h2>
        <br>
        {% endif %}
        {% endif %}

        <h2><b>Events for this course are</b></h2>
        {% for even in events %}
        <p><b>*)<u>Time added:</b></u> {{ even.date }}    {{ even.time }} </p>
        {% if even.deadline %}
        <p><b><u>Deadline:</u></b> {{ even.deadline }}</p>
        {% endif %}
        <p><b><u>Event:</b></u> {{ even.event }}</p>
        {% if even.docfile %}
        <p><a href="{{ MEDIA_URL }}{{even.docfile.url}}">Uploaded File</a></p>
        {% endif %}
        <br>
        <br>
        {% endfor %}
        <br>
        <br>

        {% if course.instructor != user %}
        <h2><b>Contact Instructor</b></h2>
            <form method="post"  action="." id="confirm">
                {% csrf_token %}
                 <table border="0">
                {{ form.as_table }}
                 </table>
                <div class="form-actions">
                  <button onclick="myFunction()">Send</button>
                
                  
                </div>
             </form>
             
             <script>
function myFunction() {
    alert("Sending mail to {{ course.instructor.email  }}");
}
</script>
        <br>
        {% endif %}
</div>

        
{% endblock %} 






     

login/templates/coursedisplay.html
{% extends "base.html" %}
{% block title %}Add Courses{% endblock %}
{% block head %}All the courses supported by the System are{% endblock %}
{% block content %}
{% for course in courses %}

   <ul class="nav">


   {% if user.is_staff %}
   <li> <a  href="/faculty/">Home</a></li>
  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
    <li> <a  href="/student/">Home</a></li>
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a class="active" href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>
    <div class="container">
        <h1><a href="{% url "login:coursedisplay" pk=course.pk %}">{{ course.name }}</a></h1>
        <p><b><u>Instructor:</u></b> {{ course.instructor.username }}</p>
        <p><b><u>Syllabus:</u></b> {{ course.syllabus }}</p>
        <p><b><u>Prerequisite:</u></b> {{ course.prerequisite.name }}</p>
        <br>
        <br>
    </div>
{% endfor %}
{% endblock %}

login/templates/courseregister.html
{% extends "base.html" %}
{% block title %}View Courses{% endblock %}
{% block head %}Register for Courses{% endblock %}
{% block content %}
    <ul class="nav">
   <li> <a  href="/student/">Home</a></li>

  <li>  <a class="active" href="/courseregister/">Register for Course</a></li>


   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>
    <div class="container">
    <form method="post" action=".">{% csrf_token %}
        <table border="0">
            {{ form2.as_table }}
        </table>
        <input type="submit" value="Register for the Course" />
    </form>
    </div>
{% endblock %}

login/templates/faculty.html
{% extends "base.html" %}
{% block title %}Welcome to University Course Management{% endblock %}
{% block head %}Welcome to University Course Management{% endblock %}
{% block content %}


    <ul class="nav">
   <li> <a class="active" href="/faculty/">Home</a></li>

   {% if user.is_staff %}

  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>




     <p class="welcome">Welcome {{ user.first_name }} !</p>

    <!--<p><b>Manage Courses</b></p>
    <a href="/addevent/">Add Course Events</a>
    <br>-->


{% endblock %}

login/templates/feesuccess.html
{% extends "base.html" %}
{% block title %}Pay fees{% endblock %}
{% block head %}Pay fees{% endblock %}
{% block content %}


<ul class="nav">


   {% if user.is_staff %}
   <li> <a  href="/faculty/">Home</a></li>
  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
    <li> <a  href="/student/">Home</a></li>
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a class ="active" href="/registeredcourses/">Your Courses</a></li>

   <li><a  href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>

<div class="container">

<p> Fees paid successfully :  {{ fees }}$  </p>
<a href='/student/'>Go to Home</a>
</div>
{% endblock %}

login/templates/parent.html
{% extends "base.html" %}
{% block title %}View Courses{% endblock %}
{% block head %}Register for Courses{% endblock %}
{% block content %}
    
    <div class="container">
    <h1>Parent Portal</h1>
    <form method='GET', action='/parent/'>
    <b>childid:</b>
    <input type="text" name="childid"><br>
    <b>emailid:</b>
    <input type="text" name="emailid">
    <br><br><button type="submit" class="btn">Login</button>
    </form>
    </div>
   
 <div class="contain"> 
{%for use in user %}
<h1>The courses registered by your child {{ use.first_name }} are</h1>
{%endfor%}
 
{% for course in regcourses %}
        <p><b><a href="{% url "login:coursedisplay" pk=course.pk %}">{{ course.name }}</a></b></p>
        <p><b><u>Syllabus:</u></b> {{ course.syllabus }}</p>
        <br>
{% endfor %}
    
   
    
{% endblock %}

login/templates/parentresult.html
{% extends "base.html" %}
{% block title %}Registered Courses{% endblock %}
{% block head %}Your Courses are{% endblock %}
{% block content %}
<h2>The result of your child {{ user.username }} is</h2>
 <div class="container">
{% for course in regcourses %}
        <h1><a href="{% url "login:coursedisplay" pk=course.pk %}">{{ course.name }}</a></h1>

        <p><b><u>Syllabus:</u></b> {{ course.syllabus }}</p>
        
        <br>
        <br>
{% endfor %}

</div>
{% endblock %}

login/templates/registeredcourses.html
{% extends "base.html" %}
{% block title %}Registered Courses{% endblock %}
{% block head %}Your Courses are{% endblock %}
{% block content %}

     <ul class="nav">


   {% if user.is_staff %}
   <li> <a  href="/faculty/">Home</a></li>
  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
    <li> <a  href="/student/">Home</a></li>
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a class ="active" href="/registeredcourses/">Your Courses</a></li>

   <li><a  href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>
 <div class="container">
{% for course in regcourses %}
        <h1><a href="{% url "login:coursedisplay" pk=course.pk %}">{{ course.name }}</a></h1>

        <p><b><u>Syllabus:</u></b> {{ course.syllabus }}</p>
        
        <br>
        <br>
{% endfor %}

{% for coursec in createdcourses %}
        <h1><a href="{% url "login:coursedisplay" pk=coursec.pk %}">{{ coursec.name }}</a></h1>
        
        <p><b><u>Instructor:</u></b> {{ coursec.instructor }}</p>
        
        <br>
        <br>
{% endfor %}
</div>
{% endblock %}

login/templates/student.html
{% extends "base.html" %}


{% block title %}Course Management{% endblock %}

{% block content %}



     <ul class="nav">
   <li> <a class="active" href="/student/">Home</a></li>

   {% if user.is_staff %}

  <li>  <a href="/courseadd/">Add Courses</a></li>
   {% else %}
  <li>  <a href="/courseregister/">Register for Course</a></li>
   {% endif %}

   <li> <a href="/registeredcourses/">Your Courses</a></li>

   <li><a href="/coursedisplay/">View all Courses</a> </li>

    <li><a href="/logout/">Logout</a></li>
    </ul>


     <p class="welcome">Welcome {{ user.first_name }} !</p>
    <div class="container">
    <h2>Upcoming Events</h2>
    {% for cour in course %}
     <h3><a href="{% url "login:coursedisplay" pk=cour.pk %}">{{ cour.cid.name }}</a></h3>
     <p><b><u>Task:</u></b>{{ cour.event }} </p>
     <p><b><u>Scheduled Date:</u></b>{{ cour.deadline }}</p>

    {%endfor%}
    </div>
{% endblock %}